### ISSUE TITLE
transactions don't load when viewing address on yogh.io

### ISSUE THREAD

**Issue by jlopp** [JornC/bitcoin-transaction-explorer#22]
Perhaps something is broken on the server? It just spins forever while trying to load transactions.

**Comment by JornC** [comment]
Hi @jlopp - the node over on yogh.io is no longer running an address index (a by-now deprecated fork of Core) and so the addresses won't work.

However, there's a new version of the explorer under development that, instead of a Core node, runs on an Electr+Core stack, which does support better indexing and addresses. A public-facing beta version of this explorer is available on https://beta.yogh.io and gets its data from the Blockstream Electr instance.

Example: https://beta.yogh.io/address/16NpRbuSJa7YbhnjA5pALtuJ13cPkcVjVo/

**Comment by jlopp** [comment]
cool, thanks
