### ISSUE TITLE
UI idea for the script interpreter

### ISSUE THREAD

**Issue by mrkent** [JornC/bitcoin-transaction-explorer#9]
This is a combination of your design + webbtc's, in a step by step interactive format. 

![image](https://cloud.githubusercontent.com/assets/1649755/13128573/890e37e8-d58b-11e5-98ce-447d884c94f2.png)

**Comment by JornC** [comment]
This looks like a very comprehensible design for showing how Script execution works.

It doesn't look like that big a change code-wise; the script interpretation views/logic are already mostly ready for it, just moving around some widgets basically. Are you intending to implement this yourself? Otherwise I could have a stab at it when I have some time.

---

Thanks for your thoughts on improving this project ;) It's most welcome. Cheers!

**Comment by mrkent** [comment]
@JornC No, wasn't planning on implementing it. It was just what I thought would make most sense to see. Good technical block explorers are hard to come by.
